server:
  shutdown: graceful
  port: 8080
management:
  server:
    port: 8080
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: tech-challenge-payment
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  cloud:
    kubernetes:
      client:
        namespace: tech-challenge-namespace
      reload:
        enabled: true
      discovery:
        all-namespaces: false
        enabled: true
        namespaces:
          - tech-challenge-namespace
    compatibility-verifier:
      enabled: false
    openfeign:
      httpclient:
        enabled: true
    config:
      enabled: false

logging:
  level:
    org.springframework: DEBUG  # Configurando nível de log DEBUG para Spring
    org.hibernate: DEBUG  # Configurando nível de log DEBUG para Hibernate